version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travelcorp_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - travelcorp
    depends_on:
      - mysql
      - redis

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: travelcorp_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - travelcorp
    depends_on:
      - app

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: travelcorp_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: travelcorp
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: travelcorp
      MYSQL_PASSWORD: travelcorp123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - travelcorp

  # Redis Service
  redis:
    image: redis:alpine
    container_name: travelcorp_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - travelcorp

  # MailHog Service (for email testing)
  mailhog:
    image: mailhog/mailhog
    container_name: travelcorp_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - travelcorp

# Docker Networks
networks:
  travelcorp:
    driver: bridge

# Volumes
volumes:
  mysql_data:
    driver: local
